version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - shortener
    networks:
      - shortener_network

  redis:
    image: redis:latest
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
      #- "${REDIS_PORT}-6382:${REDIS_PORT}"
    env_file:
      - .env
    networks:
      - shortener_network
    volumes:
      - redis-vol:/data

  shortener:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:8000"
      #    host : container
      #- "${APP_PORT}-8002:${APP_PORT}"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      #- APP_HOST=${APP_HOST:-host.docker.internal}
      # Resolves to host.docker.internal which tells the internal hostname of redis container
#      - REDIS_HOST=${REDIS_HOST:-host.docker.internal}
      - REDIS_HOST=redis
    # Comment the line below for production
    command: ["uvicorn", "backend.app.main:app", "--host", "${APP_HOST}", "--debug", "--port", "8000", "--reload-dir", "/app"]
    networks:
      - shortener_network
    volumes:
      - ./backend/app:/app/backend/app
      - ./frontend:/app/frontend

volumes:
  redis-vol:

networks:
  shortener_network:
